/* Generated by @zwents/openapi — do not edit by hand. */
export type GetHelloResponse = {
  message: string;
};

export type Problem = {
  type: string;
  title: string;
  status: number;
  code: string;
  detail?: string;
};

export type GetUsersByIdResponse = {
  id: string;
  name: string;
};

export type MinimalClientOptions = {
  baseUrl: string;
  fetch?: typeof fetch;
};

export class MinimalClient {
  readonly baseUrl: string;
  private readonly fetch: typeof fetch;

  constructor(options: MinimalClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.fetch = options.fetch ?? globalThis.fetch.bind(globalThis);
  }

  async getHello(init?: RequestInit): Promise<GetHelloResponse> {
    const url = new URL(`/hello`, this.baseUrl);
    const res = await this.fetch(url, { ...init });
    if (!res.ok) {
      throw new Error(`getHello failed: ${res.status} ${res.statusText}`);
    }
    return res.json() as Promise<GetHelloResponse>;
  }

  async getUsersById(params: { id: string }, init?: RequestInit): Promise<GetUsersByIdResponse> {
    const url = new URL(`/users/${params.id}`, this.baseUrl);
    const res = await this.fetch(url, { ...init });
    if (!res.ok) {
      throw new Error(`getUsersById failed: ${res.status} ${res.statusText}`);
    }
    return res.json() as Promise<GetUsersByIdResponse>;
  }
}
