/* Generated by zwen gen:wire — do not edit by hand. */
import { createMemoryDb } from "./db.js";
import { createNotesRepo } from "./notes-repo.js";
import { createNotesService } from "./notes-service.js";
import { createTokenService } from "./tokens.js";

export function buildContainer() {
  const db = createMemoryDb();
  const notesRepo = createNotesRepo(db);
  const tokens = createTokenService(db);
  const notes = createNotesService(notesRepo);
  return { db, notes, tokens } as const;
}
