import { buildContainer as buildGenerated } from "./container.gen.js";
import type { Db } from "./db.js";
import type { NotesService } from "./notes-service.js";
import type { TokenService } from "./tokens.js";

export type AppServices = {
  db: Db;
  notes: NotesService;
  tokens: TokenService;
};

/**
 * Composition root — generated by `zwen gen:wire` from `../wire.ts`.
 * Edit the wire manifest, then regenerate; do not hand-edit `container.gen.ts`.
 */
export function buildContainer(): AppServices {
  return buildGenerated();
}
