import path from "node:path";
import { assertSafeIdent, WireCodegenError } from "./errors.js";
import { topoSortProviders } from "./topo.js";
import type { WireGraphAst } from "./types.js";

export function emitWireContainer(
  graph: WireGraphAst,
  outPath: string,
): string {
  const ordered = topoSortProviders(graph.providers, graph.seeds);
  const expose =
    graph.expose ?? ordered.map((p) => p.key);

  for (const key of expose) {
    if (!ordered.some((p) => p.key === key) && !graph.seeds.includes(key)) {
      throw new WireCodegenError(
        `expose contains unknown key "${key}"`,
      );
    }
  }

  const factoryNames = new Set(ordered.map((p) => p.factoryName));
  const importLines = emitImports(graph, outPath, factoryNames);

  const seedParams = graph.seeds
    .map((name) => `${name}: unknown`)
    .join(", ");
  const fnName = graph.functionName;

  const lines: string[] = [
    "/* Generated by zwen gen:wire — do not edit by hand. */",
    ...importLines,
    "",
    `export function ${fnName}(${seedParams}) {`,
  ];

  for (const p of ordered) {
    const args = p.deps.join(", ");
    lines.push(`  const ${p.key} = ${p.factoryName}(${args});`);
  }

  lines.push(`  return { ${expose.join(", ")} } as const;`);
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function emitImports(
  graph: WireGraphAst,
  outPath: string,
  factoryNames: Set<string>,
): string[] {
  const byModule = new Map<
    string,
    { defaults: string[]; named: Array<{ imported: string; local: string }> }
  >();

  for (const name of factoryNames) {
    const binding = graph.imports.get(name);
    /* v8 ignore next 3 */
    if (!binding) {
      continue;
    }
    const specifier = relativizeSpecifier(
      graph.sourcePath,
      outPath,
      binding.moduleSpecifier,
    );
    const bucket = byModule.get(specifier) ?? { defaults: [], named: [] };
    if (binding.isDefault) {
      if (!bucket.defaults.includes(name)) bucket.defaults.push(name);
    } else {
      bucket.named.push({ imported: binding.importedName, local: name });
    }
    byModule.set(specifier, bucket);
  }

  const lines: string[] = [];
  for (const [specifier, bucket] of [...byModule.entries()].toSorted((a, b) =>
    a[0].localeCompare(b[0]),
  )) {
    const moduleLiteral = JSON.stringify(specifier);
    for (const local of bucket.defaults) {
      assertSafeIdent(local, "import binding");
      lines.push(`import ${local} from ${moduleLiteral};`);
    }
    if (bucket.named.length > 0) {
      const named = bucket.named
        .toSorted((a, b) => a.local.localeCompare(b.local))
        .map((n) => {
          assertSafeIdent(n.local, "import binding");
          assertSafeIdent(n.imported, "imported name");
          return n.imported === n.local
            ? n.local
            : `${n.imported} as ${n.local}`;
        })
        .join(", ");
      lines.push(`import { ${named} } from ${moduleLiteral};`);
    }
  }
  return lines;
}

function relativizeSpecifier(
  wirePath: string,
  outPath: string,
  specifier: string,
): string {
  if (!specifier.startsWith(".")) return specifier;
  const absolute = path.resolve(path.dirname(wirePath), specifier);
  let rel = path.relative(path.dirname(outPath), absolute);
  rel = rel.split(path.sep).join("/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}
